package com.fit2cloud.codedeploy2.client.model;

import java.io.Serializable;

public class ContainerResourceSecret implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.id
     *
     * 
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.name
     *
     * 
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.api_version
     *
     * 
     */
    private String apiVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.kind
     *
     * 
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.uid
     *
     * 
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.create_time
     *
     * 
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.account_id
     *
     * 
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.status
     *
     * 
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.resource_namespace_id
     *
     * 
     */
    private String resourceNamespaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.labels
     *
     * 
     */
    private String labels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.type
     *
     * 
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_resource_secret.data
     *
     * 
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_container_resource_secret
     *
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.id
     *
     * @return the value of devops_container_resource_secret.id
     *
     * 
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.id
     *
     * @param id the value for devops_container_resource_secret.id
     *
     * 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.name
     *
     * @return the value of devops_container_resource_secret.name
     *
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.name
     *
     * @param name the value for devops_container_resource_secret.name
     *
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.api_version
     *
     * @return the value of devops_container_resource_secret.api_version
     *
     * 
     */
    public String getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.api_version
     *
     * @param apiVersion the value for devops_container_resource_secret.api_version
     *
     * 
     */
    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion == null ? null : apiVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.kind
     *
     * @return the value of devops_container_resource_secret.kind
     *
     * 
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.kind
     *
     * @param kind the value for devops_container_resource_secret.kind
     *
     * 
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.uid
     *
     * @return the value of devops_container_resource_secret.uid
     *
     * 
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.uid
     *
     * @param uid the value for devops_container_resource_secret.uid
     *
     * 
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.create_time
     *
     * @return the value of devops_container_resource_secret.create_time
     *
     * 
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.create_time
     *
     * @param createTime the value for devops_container_resource_secret.create_time
     *
     * 
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.account_id
     *
     * @return the value of devops_container_resource_secret.account_id
     *
     * 
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.account_id
     *
     * @param accountId the value for devops_container_resource_secret.account_id
     *
     * 
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.status
     *
     * @return the value of devops_container_resource_secret.status
     *
     * 
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.status
     *
     * @param status the value for devops_container_resource_secret.status
     *
     * 
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.resource_namespace_id
     *
     * @return the value of devops_container_resource_secret.resource_namespace_id
     *
     * 
     */
    public String getResourceNamespaceId() {
        return resourceNamespaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.resource_namespace_id
     *
     * @param resourceNamespaceId the value for devops_container_resource_secret.resource_namespace_id
     *
     * 
     */
    public void setResourceNamespaceId(String resourceNamespaceId) {
        this.resourceNamespaceId = resourceNamespaceId == null ? null : resourceNamespaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.labels
     *
     * @return the value of devops_container_resource_secret.labels
     *
     * 
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.labels
     *
     * @param labels the value for devops_container_resource_secret.labels
     *
     * 
     */
    public void setLabels(String labels) {
        this.labels = labels == null ? null : labels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.type
     *
     * @return the value of devops_container_resource_secret.type
     *
     * 
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.type
     *
     * @param type the value for devops_container_resource_secret.type
     *
     * 
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_resource_secret.data
     *
     * @return the value of devops_container_resource_secret.data
     *
     * 
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_resource_secret.data
     *
     * @param data the value for devops_container_resource_secret.data
     *
     * 
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}