package com.fit2cloud.codedeploy2.client.model;

import java.io.Serializable;

public class ContainerPods implements Serializable {
   
    private String id;

    private String name;

    private String clusterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_pods.created_time
     *
     * 
     */
    private Long createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_pods.description
     *
     * 
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_pods.english_name
     *
     * 
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devops_container_pods.service_address
     *
     * 
     */
    private String serviceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table devops_container_pods
     *
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.id
     *
     * @return the value of devops_container_pods.id
     *
     * 
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.id
     *
     * @param id the value for devops_container_pods.id
     *
     * 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.name
     *
     * @return the value of devops_container_pods.name
     *
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.name
     *
     * @param name the value for devops_container_pods.name
     *
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.cluster_id
     *
     * @return the value of devops_container_pods.cluster_id
     *
     * 
     */
    public String getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.cluster_id
     *
     * @param clusterId the value for devops_container_pods.cluster_id
     *
     * 
     */
    public void setClusterId(String clusterId) {
        this.clusterId = clusterId == null ? null : clusterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.created_time
     *
     * @return the value of devops_container_pods.created_time
     *
     * 
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.created_time
     *
     * @param createdTime the value for devops_container_pods.created_time
     *
     * 
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.description
     *
     * @return the value of devops_container_pods.description
     *
     * 
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.description
     *
     * @param description the value for devops_container_pods.description
     *
     * 
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.english_name
     *
     * @return the value of devops_container_pods.english_name
     *
     * 
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.english_name
     *
     * @param englishName the value for devops_container_pods.english_name
     *
     * 
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devops_container_pods.service_address
     *
     * @return the value of devops_container_pods.service_address
     *
     * 
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devops_container_pods.service_address
     *
     * @param serviceAddress the value for devops_container_pods.service_address
     *
     * 
     */
    public void setServiceAddress(String serviceAddress) {
        this.serviceAddress = serviceAddress == null ? null : serviceAddress.trim();
    }
}